%% Campus With Central Plant - Plotting Script
%
% This script generates several summary plots illustrating the data
% exchanges in the campus with central plant demo. Run this script from the
% MATLAB command line in order to generate the plots.

%% Setup
% System name
sys = 'campus_with_central_plant';

% Open system
open_system(sys);

% Simulate
sim(sys);

%% Data Setup
% Transform time to hours
t = t / 3600;

% Extract data from exported workspace variables
build_1_elec_hvac     = building_1(:,13);
build_1_elec_total    = building_1(:,12);
build_2_elec_hvac     = building_2(:,13);
build_2_elec_total    = building_2(:,12);
build_1_mass_flow     = building_1(:,8);
build_1_thermal_load  = -building_1(:,9);
build_2_mass_flow     = building_2(:,8);
build_2_thermal_load  = -building_2(:,9);
plant_elec_chiller    = central_plant(:,2);

% Convert electrical power data to kW
build_1_elec_hvac     = build_1_elec_hvac / 1000;
build_1_elec_total    = build_1_elec_total / 1000;
build_2_elec_hvac     = build_2_elec_hvac / 1000;
build_2_elec_total    = build_2_elec_total / 1000;
plant_elec_chiller    = plant_elec_chiller / 1000;

% Convert thermal power data to kBTU/h
build_1_thermal_load  = build_1_thermal_load / 293.07;
build_2_thermal_load  = build_2_thermal_load / 293.07;

% Derived data
plant_mass_flow       = build_1_mass_flow + build_2_mass_flow;
plant_thermal_load    = build_1_thermal_load + build_2_thermal_load;
campus_elec_total     = build_1_elec_total + build_2_elec_total + plant_elec_chiller;

%% Plot: Single Building Electrical Power
% Create figure
figure('Units', 'in', ...
    'Position', [1 1 7 5]);
hold on;

% Create plot
line(t, build_1_elec_hvac   , ...
    'Color', 'red'          , ...
    'LineStyle', '--'       , ...
    'LineWidth', 1.2        );
line(t, build_1_elec_total  , ...
    'Color', 'blue'         , ...
    'LineWidth', 1.2        );

% Create legend
legend('HVAC', 'TOTAL');

% Labels
xlabel('Simulation Time (h)');
ylabel('Electrical Demand (kW)');
title('Electricity Consumption (Single Building)');

% Plot region setup
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'in'      , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
xlim([0, 96]);

% Finish
hold off;

% Print to file
set(gcf, ...
    'PaperUnits',       'inches'    , ...
    'PaperPosition',    [0 0 7 5]   );
print(gcf, '-dpng', '-r200', ...
    [sys '_demo_building_power.png'])

%% Plot: Thermal Load
% Create figure
figure('Units', 'in', ...
    'Position', [1 1 7 5]);
hold on;

% Create plot
line(t, build_1_thermal_load   , ...
    'Color', 'red'             , ...
    'LineStyle', '--'          , ...
    'LineWidth', 1.2           );
line(t, build_2_thermal_load   , ...
    'Color', 'blue'            , ...
    'LineStyle', '-.'          , ...
    'LineWidth', 1.2           );
line(t, plant_thermal_load     , ...
    'Color', 'black'           , ...
    'LineWidth', 1.2           );

% Create legend
legend('Building 1', 'Building 2', 'Campus');

% Labels
xlabel('Simulation Time (h)');
ylabel('Thermal Load (kBTU/h)');
title('Chilled Water Load');

% Plot region setup
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'in'      , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
xlim([0, 96]);

% Finish
hold off;

% Print to file
set(gcf, ...
    'PaperUnits',       'inches'    , ...
    'PaperPosition',    [0 0 7 5]   );
print(gcf, '-dpng', '-r200', ...
    [sys '_demo_thermal_load.png'])

%% Plot: Electrical Load
% Create figure
figure('Units', 'in', ...
    'Position', [1 1 7 5]);
hold on;

% Create plot
line(t, build_1_elec_total     , ...
    'Color', 'red'             , ...
    'LineStyle', '--'          , ...
    'LineWidth', 1.2           );
line(t, build_2_elec_total     , ...
    'Color', 'blue'            , ...
    'LineStyle', '-.'          , ...
    'LineWidth', 1.2           );
line(t, plant_elec_chiller     , ...
    'Color', 'green'           , ...
    'LineStyle', ':'           , ...
    'LineWidth', 1.2           );
line(t, campus_elec_total      , ...
    'Color', 'black'           , ...
    'LineWidth', 1.2           );

% Create legend
legend('Building 1', 'Building 2', 'Central Chiller Plant', 'Campus');

% Labels
xlabel('Simulation Time (h)');
ylabel('Electrical Demand (kW)');
title('Electrical Load');

% Plot region setup
set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'in'      , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 1         );
xlim([0, 96]);

% Finish
hold off;

% Print to file
set(gcf, ...
    'PaperUnits',       'inches'    , ...
    'PaperPosition',    [0 0 7 5]   );
print(gcf, '-dpng', '-r200', ...
    [sys '_demo_elec_load.png'])